import { ArrowUpRight, ArrowRight, Check, LayoutDashboard, Users, Receipt, Zap } from 'lucide-react';
import './visual-services.css';
const contact='/lets-talk';
export default function VisualServices(){return <section className="vs-services hp-wrap" aria-label="What we do">
  <a href={contact} className="vs-card vs-connect hp-reveal"><span className="vs-category">01 / BUSINESS TRANSFORMATION <ArrowUpRight size={22}/></span><div className="vs-demo vs-network" aria-hidden="true"><div className="vs-tools"><span><Users size={19}/>Sales</span><span><LayoutDashboard size={19}/>Operations</span><span><Receipt size={19}/>Finance</span></div><div className="vs-connectors"><i/><i/><i/></div><div className="vs-hub"><span className="vs-hub-icon"><Check size={20}/></span><span>One shared picture<small>Everyone in sync.</small></span></div><span className="vs-mini-note">ah, that’s better.</span></div><h3>Everything,<br/><em>connected.</em></h3><p>Your tools and teams. Finally on the same page.</p><span className="vs-bottom">Bring it all together <ArrowRight size={16}/></span></a>
  <a href={contact} className="vs-card vs-custom hp-reveal"><span className="vs-category">02 / CUSTOM SOFTWARE <ArrowUpRight size={22}/></span><div className="vs-demo vs-app" aria-hidden="true"><div className="vs-app-top"><span><i/><i/><i/></span><small>Made for your team</small></div><div className="vs-app-body"><div className="vs-sidebar"><LayoutDashboard size={17}/><Users size={17}/><Receipt size={17}/></div><div className="vs-modules"><span className="vs-module vs-module-a">Your workflow <Check size={13}/></span><span className="vs-module vs-module-b">Your people</span><span className="vs-module vs-module-c">Your way <ArrowUpRight size={13}/></span></div></div><span className="vs-fit-label">A proper fit. ↗</span></div><h3>Your business.<br/><em>Your software.</em></h3><p>Web and mobile apps shaped around your people.</p><span className="vs-bottom">Make it your own <ArrowRight size={16}/></span></a>
  <a href={contact} className="vs-card vs-automate hp-reveal"><span className="vs-category">03 / AUTOMATION & APPLIED AI <ArrowUpRight size={22}/></span><div className="vs-demo vs-workflow" aria-hidden="true"><div className="vs-auto-title"><Zap size={17}/><span>Busywork, handled.</span><span className="vs-auto-badge">AUTO</span></div><div className="vs-auto-row"><span>Copy the details</span><Check size={17}/></div><div className="vs-auto-row"><span>Send the reminder</span><Check size={17}/></div><div className="vs-auto-row"><span>Update the report</span><Check size={17}/></div><span className="vs-time-note">More room for the good stuff.</span></div><h3>Less repeat.<br/><em>More headspace.</em></h3><p>Let the routine run. Let your team get on with it.</p><span className="vs-bottom">Take the repeat out <ArrowRight size={16}/></span></a>
  <p className="vs-caption">A few possibilities, illustrated. Every solution starts with your business.</p>
</section>}
